export const employeeInitialValues = {
  email: "",
  project: "",
  full_name: "",
  profession: "",
  phoneNumber: "",
  next_of_kin_name: "",
  next_of_kin_phone: "",
  additional_skills: "",
  bank: "",
  account_number: "",
  tinNumber: "",
  NSSF_number: "",
  gender: "",
  other_languages: [],
  preferred_language: "",
};
