export const clvInitialValues = {
  last_name: "",
  first_name: "",
  gender: "",
  nationality: "",
  NIN: "",
  phoneNumber: "",
  email: "",
  city: "",
  address: "",
  district: "",
  subcounty: "",
  village: "",
  zone: "",
  profession: "",
  year_of_training: "",
  project: "",
  training_category: "",
  recruitmentDate: "",
  expiryDate: "",
  isAtive: "",
};
