export const caseFilesColumns = [
  { Header: "CASE ID", accessor: "id" },
  { Header: "SURNAME", accessor: "surname" },
  { Header: "FIRST NAME", accessor: "first_name" },
  { Header: "GENDER", accessor: "gender" },
  { Header: "NATIONALITY", accessor: "nationality" },
  {
    id: "date_opened",
    Header: "DATE OPENED",
    accessor: (d) => new Date(d.date_opened).toLocaleString(),
  },
  { Header: "CONTACT", accessor: "contact" },
  { Header: "DISTRICT", accessor: "district" },
  { Header: "DISABILITY", accessor: "disability" },
  { Header: "AGE", accessor: "age" },
  {
    id: "createdAt",
    Header: "CREATED AT",
    accessor: (d) => new Date(d.createdAt).toLocaleString(),
  },
  { Header: "FILE OPENED", accessor: "file_opened" },
  { Header: "BENEFICIARIES", accessor: "num_beneficiaries" },
  { Header: "OCCUPATION", accessor: "occupation" },
  { Header: "CASE NATURE", accessor: "case_nature" },
  { Header: "ACTION TAKEN", accessor: "action_taken" },
  { Header: "NEXT VISIT", accessor: "next_visit" },
  { Header: "REFERRED TO", accessor: "referred_to" },
  { Header: "REASON FOR REFERRAL", accessor: "reason_for_referral" },
  { Header: "FEEDBACK", accessor: "follow_up_feedback" },
  { Header: "CLOSING DATE", accessor: "file_closing_date" },
  { Header: "MOBILE CONTACT", accessor: "mobile_contact" },
  { Header: "RESPONDENT FIRST NAME", accessor: "respondent_f_name" },
  { Header: "RESPONDENT SURNAME", accessor: "respondent_s_name" },
  { Header: "RESPONDENT CONTACT", accessor: "respondent_contact" },
];
