export const caseFilesColumns = [
  { Header: "CASE ID", accessor: "id" },
  { Header: "NAME", accessor: "complainantName" },
  { Header: "FIRST NAME", accessor: "first_name" },
  { Header: "GENDER", accessor: "gender" },
  {
    id: "createdAt",
    Header: "CREATED AT",
    accessor: (d) => new Date(d.createdAt).toLocaleString(),
  },
  { Header: "NATIONALITY", accessor: "nationality" },
  { Header: "CONTACT", accessor: "contact" },
  { Header: "DISTRICT", accessor: "clvDistrict" },
  { Header: "DISABILITY", accessor: "disability" },
  { Header: "AGE", accessor: "age" },
  { Header: "FILE OPENED", accessor: "file_opened" },
  { Header: "BENEFICIARIES", accessor: "num_beneficiaries" },
  { Header: "OCCUPATION", accessor: "occupation" },
  { Header: "CASE NATURE", accessor: "case_nature" },
  { Header: "ACTION TAKEN", accessor: "action_taken" },
  { Header: "NEXT VISIT", accessor: "next_visit" },
  { Header: "REFERRED TO", accessor: "referred_to" },
  { Header: "REASON FOR REFERRAL", accessor: "reason_for_referral" },
  { Header: "FEEDBACK", accessor: "follow_up_feedback" },
  { Header: "CLOSING DATE", accessor: "file_closing_date" },
  { Header: "MOBILE CONTACT", accessor: "mobile_contact" },
  { Header: "RESPONDENT NAME", accessor: "respondentName" },
  { Header: "RESPONDENT SEX", accessor: "respondentSex" },
  { Header: "RESPONDENT AGE", accessor: "respondentAge" },
  { Header: "RESPONDENT PHONE", accessor: "respondentPhone" },
  { Header: "RESPONDENT JOB", accessor: "respondentJob" },
  { Header: "RESPONDENT COUNTRY", accessor: "respondentCountry" },
  { Header: "RESPONDENT DISTRICT", accessor: "respondentDistrict" },
  { Header: "RESPONDENT COUNTY", accessor: "respondentCounty" },
  { Header: "RESPONDENT VILLAGE", accessor: "respondentVillage" },
  { Header: "RESPONDENT PLACE OF WORK", accessor: "respondentPlaceOfWork" },
  { Header: "RESPONDENT MARTIAL STATUS", accessor: "respondentMaritalStatus" },
  {
    Header: "RESPONDENT NO. OF BENEFICIARIES",
    accessor: "respondentNumberOfBeneficiaries",
  },
  {
    Header: "RESPONDENT LEVEL OF EDUCATION",
    accessor: "respondentLevelOfEducation",
  },
  { Header: "RESPONDENT LANGUAGE", accessor: "respondentLanguage" },
];
