export const leaveTrackerColumns = [
  { Header: "Name", accessor: "name" },
  { Header: "Annual Leave Days", accessor: "annualLeaveDays" },
  { Header: "Paternal Leave Days", accessor: "paternalLeaveDays" },
  { Header: "Maternal Leave Days", accessor: "maternalLeaveDays" },
  { Header: "Jan", accessor: "jan" },
  { Header: "Feb", accessor: "feb" },
  { Header: "Mar", accessor: "mar" },
  { Header: "Apr", accessor: "apr" },
  { Header: "May", accessor: "may" },
  { Header: "Jun", accessor: "jun" },
  { Header: "Jul", accessor: "jul" },
  { Header: "Aug", accessor: "aug" },
  { Header: "Sep", accessor: "sep" },
  { Header: "Oct", accessor: "oct" },
  { Header: "Nov", accessor: "nov" },
  { Header: "Dec", accessor: "dec" },
  { Header: "Total", accessor: "total" },
];
