export const caseFilesColumns = [
  { Headers: "File No.", accessor: "fileNo" },
  { Headers: "Date Uploaded", accessor: "dateUploaded" },
  { Headers: "Village & SubCounty", accessor: "villageSubCounty" },
  { Headers: "District Of Origin", accessor: "districtOfOrigin" },
  { Headers: "Nationality", accessor: "nationality" },
  { Headers: "NIN", accessor: "nin" },
  { Headers: "File type", accessor: "fileType" },
  { Headers: "Date of opening", accessor: "dateOfOpening" },
  { Headers: "Case Number", accessor: "caseNumber" },
  { Headers: "Gender", accessor: "gender" },
  { Headers: "Name", accessor: "name" },
  { Headers: "Age", accessor: "age" },
  { Headers: "No. of beneficiaries", accessor: "noOfBeneficiaries" },
  { Headers: "Occupation", accessor: "occupation" },
  { Headers: "Nature of problem", accessor: "natureOfProblem" },
  { Headers: "Action taken", accessor: "actionTaken" },
  { Headers: "Next visit", accessor: "nextVisit" },
  { Headers: "Legal Officer", accessor: "legalOfficer" },
  { Headers: "Referred by", accessor: "referredBy" },
  { Headers: "Reason for referral", accessor: "reasonForReferral" },
  { Headers: "Follow up feedback", accessor: "followUpFeedback" },
  { Headers: "File closing date", accessor: "fileClosingDate" },
  { Headers: "Phone Number", accessor: "phoneNumber" },
  { Headers: "Disability", accessor: "disability" },
  { Headers: "Respondent Name", accessor: "respondentName" },
  { Headers: "Respondent Phone Number", accessor: "respondentPhoneNumber" },
  { Headers: "How did you find fida", accessor: "howDidYouFindFida" },
];
