export const complainantInitialValues = {
  name: "",
  sex: "",
  email: "",
  age: "",
  phoneNumber: "",
  address: "",
  country: "",
  NIN: "",
  district: "",
  subcounty: "",
  parish: "",
  village: "",
  marital_status: "",
  accompaniedBy: "",
  occupation: "",
  place_of_work: "",
  level_of_education: "",
  preferred_language: "",
  num_beneficiaries: "",
//   disability: "",
//   relationship_with_respondent: "",
};
